openapi: "3.0.0"
info:
  description: "This is the Tock NLP ADMIN API. You can manage your model with it!"
  version: "19.9"
  title: "Tock NLP ADMIN API"
  termsOfService: "https://doc.tock.ai"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/rest/admin"
tags:
  - name: "Application"
    description: "Manage application models"
  - name: "Sentence"
    description: "Manage sentences of the model"
  - name: "Dump"
    description: "Upload model dumps"

schemes:
  - "http"
  - "https"
components:
  securitySchemes:
    basicAuth:     
      type: http
      scheme: basic
security:
  - basicAuth: []
paths:
  /applications:
    get:
      tags:
        - "Application"
      summary: "Retrieve all applications of the namespace"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/definitions/ApplicationWithIntents"
  /application/{applicationId}:
    get:
      tags:
        - "Application"
      summary: "Retrieve application that matches given identifier"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "applicationId"
          in: "path"
          description: "Application identifier"
          required: true
          schema:
            type: "string"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"
              schema:
                $ref: "#/definitions/ApplicationWithIntents"

    delete:
      tags:
        - "Application"
      summary: "Delete application that matches given identifier"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "applicationId"
          in: "path"
          description: "Application identifier"
          required: true
          schema:
            type: "string"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"

  /application:
    post:
      tags:
        - "Application"
      summary: "Create or update application"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Application content"
          required: true
          schema:
            $ref: "#/definitions/ApplicationWithIntents"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"
              schema:
                $ref: "#/definitions/ApplicationWithIntents"

  /application/dump/{applicationId}:
    get:
      tags:
        - "Application"
      summary: "Retrieve full application dump that matches given identifier"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "applicationId"
          in: "path"
          description: "Application identifier"
          required: true
          schema:
            type: "string"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"
              schema:
                type: "object"

  /application/{applicationId}/intent/{intentId}:
    delete:
      tags:
        - "Application"
      summary: "Remove an intent from an application model. If the intent does not belong to an other model, delete the intent."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "applicationId"
          in: "path"
          description: "Application identifier"
          required: true
          schema:
            type: "string"
        - name: "intentId"
          in: "path"
          description: "Intent identifier"
          required: true
          schema:
            type: "string"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"
              schema:
                type: "object"

  /application/{applicationId}/intent/{intentId}/entity/{entityType}/{role}:
    delete:
      tags:
        - "Application"
      summary: "Remove a entity role from intent of an application model."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "applicationId"
          in: "path"
          description: "Application identifier"
          required: true
          schema:
            type: "string"
        - name: "intentId"
          in: "path"
          description: "Intent identifier"
          required: true
          schema:
            type: "string"
        - name: "entityType"
          in: "path"
          description: "Entity type qualified name"
          required: true
          schema:
            type: "string"
        - name: "role"
          in: "path"
          description: "Role of the entity to remove"
          required: true
          schema:
            type: "string"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"
              schema:
                type: "object"

  /sentences/dump/{dumpType}/{applicationId}/{intent}/{locale}:
    get:
      tags:
        - "Sentence"
      summary: "Retrieve qualified sentences dump that matches given application identifier, intent and locale"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "dumpType"
          in: "path"
          description: "Dump type"
          required: true
          schema:
            type: "string"
            enum: [full, obfuscated]
        - name: "applicationId"
          in: "path"
          description: "Application identifier"
          required: true
          schema:
            type: "string"
        - name: "intent"
          in: "path"
          description: "Intent name"
          required: false
          schema:
            type: "string"
        - name: "locale"
          in: "path"
          description: "Locale"
          required: false
          schema:
            type: "string"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"
              schema:
                type: "object"

  /dump/application:
    post:
      tags:
        - "Dump"
      summary: "Upload a complete application model"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      responses:
        200:
          content:
            application/json:
              description: "successful operation"
  /dump/application/{name}:
    post:
      tags:
        - "Dump"
      summary: "Upload complete application dump and set specified name as application name"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      parameters:
        - name: "name"
          in: "path"
          description: "Application name"
          required: true
          schema:
            type: "string"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"

  /dump/sentences:
    post:
      tags:
        - "Dump"
      summary: "Upload a complete application model [sentences dump format]"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      responses:
        200:
          content:
            application/json:
              description: "successful operation"
  /dump/sentences/{name}:
    post:
      tags:
        - "Dump"
      summary: "Upload complete application dump [sentences dump format] and set specified name as application name"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      parameters:
        - name: "name"
          in: "path"
          description: "Application name"
          required: true
          schema:
            type: "string"
      responses:
        200:
          content:
            application/json:
              description: "successful operation"

definitions:
  ApplicationWithIntents:
    type: "object"
    description: "An application with supported intents"
    required: [ "_id", "name", "namespace", "intents", "supportedLocales", "nlpEngineType" ]
    properties:
      _id:
        type: "string"
        description: "The id of the app"
      namespace:
        type: "string"
        description: "The namespace of the application"
      applicationName:
        type: "string"
        description: "The name of the application"
      intents:
        type: "array"
        description: "The intent definitions of the application"
        items:
          $ref: "#/definitions/IntentDefinition"
      supportedLocales:
        type: "array"
        description: "The locales supported by the application"
        items:
          type: "string"
      nlpEngineType:
        type: "object"
        description: "The current nlp engine used to build the model"
        properties:
          name:
            type: "string"
            description: "he unique name of nlp engine"
      mergeEngineTypes:
        type: "boolean"
        description: "Is intent entity model and standalone entity models are used to find the better values ?"
      useEntityModels:
        type: "boolean"
        description: "Is standalone entity models used? Useful for entity disambiguation"
      supportSubEntities:
        type: "boolean"
        description: "Does this app support sub entities ?"

  IntentDefinition:
    type: "object"
    description: "An intent definition"
    required: [ "name", "namespace", "applications", "entities" ]
    properties:
      name:
        type: "string"
        description: "The name of the intent"
      namespace:
        type: "string"
        description: "The namespace of the intent"
      category:
        type: "string"
        description: "The category of the intent"
      _id:
        type: "string"
        description: "Technical identifier"
      applications:
        type: "array"
        description: "The application ids using this intent"
        items:
          type: "string"
      entities:
        type: "array"
        description: "The entity definitions of the intent"
        items:
          $ref: "#/definitions/EntityDefinition"
      mandatoryStates:
        type: "array"
        description: "The optional mandatory states"
        items:
          type: "string"
      sharedIntents:
        type: "array"
        description: "The optional shared intents names"
        items:
          type: "string"

  EntityDefinition:
    type: "object"
    description: "An entity definition"
    required: [ "entityTypeName", "role"]
    properties:
      entityTypeName:
        type: "string"
        description: "The qualified name of the entity type"
      role:
        type: "string"
        description: "The role"
      atStartOfDay:
        type: "boolean"
        description: "To evaluate time for entity date types"

externalDocs:
  description: "Find out more about Tock"
  url: "https://theopenconversationkit.github.io/tock"
